### ISSUE TITLE
Viewer/example can break due to case-sensitivy of host in Lambda event

### ISSUE THREAD

**Issue by kokoalberti** [vincentsarago/lambda-tiler#10]
The example and viewer pages were not working while I was experimenting with this a bit. It turned out the `endpoint` being passed to the template was empty due to the incoming Lambda `event["headers"]` having a lowercase `host` key, whereas the app expects a `Host` key.

I'm guessing it's a browser thing (e.g. https://github.com/serverless/serverless/issues/2765). Using Firefox here and all the keys in the `headers` are lowercased, whereas in the `multiValueHeaders` they are not.

**Comment by vincentsarago** [comment]
this is I think due to a breaking change I push in https://github.com/vincentsarago/lambda-proxy/blob/master/lambda_proxy/proxy.py#L581-L587

this is how to do it now https://github.com/developmentseed/cogeo-mosaic/blob/master/cogeo_mosaic/utils.py#L31-L38

**Comment by vincentsarago** [comment]
@kokoalberti I just commited some change and it should now be 👍 
ref: https://github.com/vincentsarago/lambda-tiler/commit/1c5ae138bc39cdd02f0a6cd7d8f30caf87472bd5
