### ISSUE TITLE
Tiling from private bucket (S3 Signed URLs)

### ISSUE THREAD

**Issue by geospatial-jeff** [vincentsarago/lambda-tiler#8]
I'd like to dynamically tile some COGs stored in a private S3 bucket (no public access).  I'm trying to do so with S3 signed URLs:

`https://{bucket}.s3.amazonaws.com/{key}?AWSAccessKeyId={val}&Signature={val}&Expires={val}`

This is causing an error when the URL is passed to lambda-proxy because `AWSAccessKeyId`, `Signature` and `Expires` are being treated as arguments rather than part of the URL:

`[lambda-tiler] - [ERROR] - bounds_handler() got an unexpected keyword argument 'Expires'`

I'm not set on using S3 Signed URLs in particular, so if there is a better way of authenticating a private bucket for use with the tiler which currently works please let me know.

**Comment by geospatial-jeff** [comment]
I managed to get this working on single-band COGs by encoding the `&` as `%26`.  Lambda-proxy no longer mistakes the S3 signed URL parameters as arguments and the tiler can successfully read and tile the image.

This fix does not work on multi-band COGs, and returns the following error:
`[lambda-tiler] - [ERROR] - HTTP response code: 403 - Failed writing header`

**Comment by vincentsarago** [comment]
thanks for the issue @geospatial-jeff, 
Sadly this is a lambda-proxy issue, not sure there is an easy fix for this sadly. 

please feel free to open an issue on lambda-proxy repo
